### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ghost** [KuroZen/r34-json-api#1]
the https://r34-json-api.herokuapp.com site is down

**Comment by kurozenzen** [comment]
Yeah... I noticed that.

So here is the story: I actually somehow forgot my password for KuroZen, which held me from developing this project. I don't know how i did that but it happened. 

Today, I finally made a new account because google didn't give me access to KuroZen. I forked both repos and got them to work again. I even improved the stability (but in a hacky way) for now, so the new site should run no matter what happens.

**New API:** [heroku](https://custom-r34-api.herokuapp.com/) - [GitHub Repo](https://github.com/kurozenzen/r34-json-api)

**New Site:** [Site](https://kurozenzen.github.io/r34/) - [GitHub Repo](https://github.com/kurozenzen/r34)

Sorry, for being retarded...
